travis:
  secure:
    BINSTAR_TOKEN: 0S65SsAUv6j3insLVMKVlXQi5Td5k96NKdqAvMjRoSvm40zuenoAXz/4vrDLZpYMtSfQzQyxFzhWau+WG3g0RHgJyBt/frBhOgjGkbt1zhxFC89hndSWKjhIOROlfM9A8QCrX/rht4OxnJOAYxKNLy5c9GaOG2SbGVMwMUwAH1lzmVOovGOuMy4RUEj66tqj0impKq5BSU9a6Rh2k+V0mntHGvgPsilGCgGoORwC9qhZmJjVhskWN+Nv9LE+wTOJh8bj9f5lNeXSMi5ciXygW8jdFWLIwPf32WZ7io+H3w65o22FHdUKrjnvACFsdJeRTdxyPuWzo0poTx4/sp4V9CEyF+t4JK9d5KHectbfnhDckJ514Fltsq2jh+TxTaxlFXF39lxvVp11kziyhasmNR9YdvfylRJkK233/8cJbMCauJDshl8X3XlFk8xfzySb+nRrkTL1e0G8RkjMZe+An29XwpQU/yBN1x7IDtrvuvdYPMcloHgvY93Vw49hKjab+jDOhPmfZdL/nl9DB0SCyftkHWi/bkPFLixUA3zCtrKN7+FQLkSMdyLY9I1C0zLIy4RAzD9j43jGPFeFjOl1ypSoM0j6vEKLBXRIn74c235vaSZXTjTB149F6hk8iLMbUN2QXaMoQDGTdhAaShd08F+V3i6fNRlfTcjv+NIM/0M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
