appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: CaCm9lmFGystIYFXSqxqo33MmQ9IDo8n4kFXUhhoWPnLFltCPWhwX1UY4wZMnAZnSX8ZWDl3WkTNDDFl6gcNSe3K/mVNQXoAnDvV+JFA+DCxjZt6wu0J+rWZyvZTQYwy+WndHwPYDa0kpGclEbJew8x0am3sZD9AO2XcaYlUEr9PFyEKu++pChQNJa8gnMjyKk41QfqTDxM7p086tulIPWmCN3C+XhVNFhFHqD3rWidu5J+iyiFp6HVx+oDKG68066ef+0ENflALG9IyBixHQgBZ9N2Vh4XywhQns4RSZ1s7iGagnk6VkklRxdJInSKnva1+NU0f/I85QIoTtfpw5jzarPTVt7RpGM1YXU1bIkXBgBjGM5MUTDO+uH5XHpPPzqv7GA+Gwm+IEzxd2frEPfx+/Vkb1hVCnmPNebJ+lQ7RGA1hk5novz22c4w7OJ+N9bCyEAHgIV4tpNG29u2krH/1o+kEv9XrR+rG4tFD6ZkA3pdaf5UBJN4n3HeYsEbdkhPFAHQ5i+dhbIgRVNBGNXWHDb84hiK5ieFy4NFn+0zbbWmVxiEXqteVYbyyfdSByIWQ3G48H4LHkwxemeuKFytCCi+PvB4DUOKL4g3qziP7uI66eT9u5kTE07hBj6EO+GwQ55/cOtg1dLTMaCBFT1coO432AWowZvEon2PNeOY=}
